### PR TITLE
Fix Color Contrast ratio of View all Projects/Careers links

### PR DESCRIPTION
**Pull request by rahulpundir019**
Fixed Color Contrast ratio of View all Projects/Careers links to resolve this bug #134 
 
**Before Fix 2 Fail instances from AI Tool:**
image

**After Fix 0 Fail instances from AI Tool:**
image

### CODE REVIEW

**Comment by willnorris** [comment]
Hey, thanks for the contribution, and in particular the attentiveness to accessibility!  However, these colors are set by the Feather UI framework that we use at Twitter in accordance with our official brand guidelines.  So changing colors (in particular, the main Twitter Blue color) is not something we are likely to do, though I can follow up with our internal design teams about the contrast issue.

I recall looking into this specific color combination (white text of blue) sometime last year and found a really interesting article that talked about a few combinations that fail the online contrast tests, but are perceived as more legible than other combinations which do pass the online tests.  I'll see if I can dig that up, at it convinced me that this isn't actually as much of a problem as webaim and similar tools would suggest.

**Comment by willnorris** [comment]
Ah, I think it was this article: https://uxmovement.com/buttons/the-myths-of-color-contrast-accessibility/

Which is then refuted in this article: https://www.creativejuiz.fr/blog/en/user-experience/there-is-no-myths-of-color-contrast-accessibility. (I think, I just came across it and haven't read it closely yet.  Guess I have some reading to do :) )

**Comment by willnorris** [comment]
I just checked, and it looks like there is an updated version of Feather that changes this background to a slightly darker #1d9bf0, which does pass at least at larger font size: https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=1D9BF0

So I'll work on getting that updated, and then see where that leaves things.

**Comment by willnorris** [comment]
Okay, I've pushed latest version of Feather, which brings the contrast ratio to 3:1.  That might be the best we can do for right now.

**Comment by willnorris** [comment]
oops, never mind.  I just noticed that broke dark mode so I've rolled it back.  I'll try again later in the week.

**Comment by rahulpundir019** [comment]
Thanks, @willnorris 

I still suggest using #0B77D8(better UX) or #137ab9(to just pass the color contrast) for the 'View all Projects/Careers' links background color given the fact that you are using the dark theme as default theme for your website.

Although 3:1 will also not comply with WCAG.

I am aware of the above contrast myths as working in Accessibility QA and I also respect your team's decision if you are not comfortable changing these control's color contrast. 

Current UX:
image

Expected UX:
image

**Comment by willnorris** [comment]
I appreciate the suggestion, but we're going to follow Twitter's official brand colors.  I'm aware that this contrast level (at this font size) doesn't meet WCAG level AA.

**Comment by willnorris** [comment]
Just to follow up on this, it looks like the latest UI style at Twitter has actually moved to black and white buttons, and the blue buttons are only used in very limited scenarios like the "Tweet" button on twitter.com.  So that is now reflected on the open source site, which incidentally also addresses the accessibility issues 😄 

We still have the white text on blue background in other areas, but that's outside what this specific PR was discussing and something we'll have to address later.

**Comment by rahulpundir019** [comment]
Thanks for update. Yup issue is fixed now.

**Pull request closed without merging**
